version: '3.9'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anomaly_flask
    expose:
      - "9500"
    environment:
      - FIREWALL_URL=https://fortigate.example.com

  nginx:
    image: nginx:latest
    container_name: anomaly_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask_app
    ports:
      - "9500:80"
