version: '3.9'

services:
  flask-app:
    build: .
    container_name: flask-app
    environment:
      FIREWALL_URL: "https://fortigate.example.com"
      SIEM_TYPE: "elastic"
      ELASTIC_URL: "http://localhost:9200/firewall-logs/_doc"
      CORTEX_URL: "http://cortex.example.com/api/logs"
      SPLUNK_URL: "http://splunk.example.com:8088/services/collector"
      SENTINEL_URL: "https://sentinel.example.com/api/logs"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - ./logs:/var/log
    depends_on:
      - redis

  model-backend:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: model-backend
    command: python eudaemons.py
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
      - model-backend

volumes:
  redis_data:
