version: '3.9'

services:
  flask-app:
    build: .
    container_name: eudaemons_flask
    environment:
      FIREWALL_URL: "https://fortigate.example.com"
      SIEM_TYPE: "elastic"
      ELASTIC_URL: "http://localhost:9200/firewall-logs/_doc"
      CORTEX_URL: "http://cortex.example.com/api/logs"
      SPLUNK_URL: "http://splunk.example.com:8088/services/collector"
      SENTINEL_URL: "https://sentinel.example.com/api/logs"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - ./logs:/eudaemons/logs
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: eudaemons_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: eudaemons_nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
